-- Si se_language ya existe, lo dejamos como está. Si no existe, creamos la tabla.
se_language = se_language or {}

-- Creamos la sub-tabla para este idioma específico
se_language.es = {} -- En el archivo inglés pon se_language.en = {}, etc.

se_language.es["BuyFuelMain"] = "Bienvenidos, viajeros. Revisen lo que tenemos disponible."
se_language.es["BuyFuel"] = "Comprar combustible"
se_language.es["RepairShip"] = "Reparar nave"
se_language.es["PirateShip"] = "Despues del salto hiperespacial, se encuentran con una nave enemiga. Su capitan transmite frases amenazantes en un idioma desconocido."
se_language.es["AsteroidColonyMain"] = "Bienvenidos. Tenemos un problema: el combustible se esta agotando en todas las naves de la estacion y no encontramos nada cerca. Pueden ayudarnos?"
se_language.es["Givefuel"] = "Entregar combustible"
se_language.es["AsteroidColonyThanks"] = "Gracias, viajeros. Aqui tienen su pago."
se_language.es["AsteroidColonyLie"] = "Eran mentirosos. Despues de entregarles combustible, la senal de la estacion empieza a desvanecerse."
se_language.es["Deny"] = "Rechazar"
se_language.es["AsteroidColonyNotMad"] = "De acuerdo, no estamos tan molestos con ustedes."
se_language.es["AsteroidColonyMad"] = "El capitan de la colonia se enfurece y de pronto detectan un pequeno cohete impactando contra la nave."
se_language.es["ShipInAsteroidBelt"] = "Despues del salto hiperespacial encuentran una nave intentando salir de un campo de asteroides. Dicen que sus escudos estan caidos y no resistiran mucho."
se_language.es["SaveShip"] = "Salvar la nave"
se_language.es["ShipInAsteroidBeltSaved"] = "Lograron salvar la nave, aunque la suya quedo bastante danada. La tripulacion esta agradecida y les entrega algunos recursos."
se_language.es["ShipInAsteroidBeltNotSaved"] = "No lograron salvar la nave. Choco contra un asteroide enorme y la comunicacion se pierde."
se_language.es["FlyAway"] = "Alejarse"
se_language.es["ShipInAsteroidBeltFlyAway"] = "Dejaron la nave atras. Quizas sobrevivan."
se_language.es["ScienceStationMain"] = "Escuchan voces por el comunicador. Es un grupo de cientificos que estudia los efectos de los viajes espaciales prolongados en humanos."
se_language.es["TakeAPart"] = "Participar en la investigacion"
se_language.es["ScienceStationMainTakeAPart"] = "Los cientificos estan muy agradecidos. Les entregan recursos por la ayuda."
se_language.es["ScienceStationMainPirates"] = "No eran cientificos, eran piratas. Al acercarse, abren fuego."
se_language.es["DebyInvite"] = "Rechazan la invitacion."
se_language.es["PiratesInAsteroidsMain"] = "Despues del salto hiperespacial encuentran una nave pirata atrapada entre asteroides. Sus escudos estan caidos y podrian destruirlos."
se_language.es["SavePirateShip"] = "Liberarlos de los asteroides"
se_language.es["PiratesInAsteroidsGrateful"] = "Los piratas estan agradecidos y les entregan algunos recursos."
se_language.es["PiratesInAsteroidsAttack"] = "Despues de liberarlos, los piratas atacan."
se_language.es["DestroyThem"] = "Destruirlos"
se_language.es["PiratesInAsteroidsAttackDestroyThem"] = "Decidieron que los piratas no valian el riesgo y los destruyeron."
se_language.es["PiratesInAsteroidsAttackDestroyThemFriends"] = "Destruyeron a los piratas, pero sus aliados empiezan a aparecer en el radar."
se_language.es["FireOnScienceStationMain"] = "Escuchan voces por el comunicador. Cientificos de una estacion informan que el fuego esta fuera de control y el sistema antiincendios no responde."
se_language.es["TrySaveScientists"] = "Salvar cientificos"
se_language.es["FireOnScienceStationMainTrySaveScientistsGr"] = "Los cientificos estan muy agradecidos y les entregan recursos por la ayuda."
se_language.es["FireOnScienceStationMainTrySaveScientistsFail"] = "No pudieron salvar a los cientificos. El sistema de puertas tampoco responde y no pueden entrar a la nave."
se_language.es["FireOnScienceStationMainTrySaveScientistsPirates"] = "No eran cientificos, eran piratas. Al acercarse, abren fuego."
se_language.es["Leave"] = "Irse"
se_language.es["FireOnScienceStationMainLeave"] = "Decidieron dejar la estacion atras."
se_language.es["BugsAtStationMain"] = "Escuchan voces por el comunicador. La estacion mas cercana fue tomada por criaturas y la tripulacion pide ayuda."
se_language.es["FireOnScienceTrySavePeople"] = "Salvar a la gente de la estacion"
se_language.es["FireOnScienceTrySavePeopleDock"] = "Decidieron acoplarse a la estacion y rescatar a la gente. Estan muy agradecidos."
se_language.es["FireOnScienceTrySavePeopleDockDead"] = "Decidieron acoplarse a la estacion, pero al llegar ya no quedaba nadie con vida."
se_language.es["BugsOnAsteroids"] = "Despues del salto hiperespacial encuentran un asteroide gigante lleno de criaturas. Estan por todas partes. Chocan contra el asteroide y algunas entran a la nave."
